import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { places } from '../data/placesData.js';
import PlaceCard from '../components/placeCard';
import { useRouter } from 'next/router';
const Home: NextPage = () => {
	const router = useRouter();
	return (
		<div>
			<Head>
				<title>Travel Plus | Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='w-100% h-96 relative'>
				<Image
					src='/images/hero.jpg'
					layout='fill'
					objectFit='cover'
					alt='Hero Image'
					priority={true}
				/>
			</div>
			<div
				className='grid 
      place-items-center 
      sm:grid-cols-2 
      lg:grid-cols-3 
      lg:px-32'
			>
				{places.map((place, idx) => (
					<PlaceCard key={idx} {...place} />
				))}
			</div>
		</div>
	);
};

export default Home;
